### ISSUE TITLE
Could you share the NeRF-360-v2 dataset? The original link is dead.

### ISSUE THREAD

**Issue by Totoro97** [kakaobrain/nerf-factory#6] opened 2022-10-18 04:57 UTC
Thank you in advance!

**Comment by jeongyw12382** [comment] 2022-10-18 08:48
Have you tried the automatic download script that we have provided? 

https://github.com/kakaobrain/NeRF-Factory#preparing-dataset

It works fine on my env. Let me know if you have any problems of using this automatic script.

Or you could directly get the data from the link below:
http://storage.googleapis.com/gresearch/refraw360/360_v2.zip

**Comment by Totoro97** [comment] 2022-10-18 08:52
Oh Thanks so much! I was not aware the download script.

**Comment by jeongyw12382** [comment] 2022-10-18 10:39
Glad that the issue is solved :) 
Closing the issue.

**Closed as completed by jeongyw12382** 2022-10-18 10:39 UTC
