### ISSUE TITLE
Multiple errors occurred 

### ISSUE THREAD

**Issue by Cerf-Volant425** [kakaobrain/nerf-factory#18] opened 2022-12-25 01:00 UTC
Many thanks for your awesome work ! I ran into several errors when training and testing the model for the tnt dataset.

1. When I use my custom tnt dataset with the NeRF++/Mipnerf360 models, the loss is always NAN
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/79494908/209454374-800f2723-e762-4856-ab46-08ed626151f8.png">

2. When I render the video by 
`python3 run.py --ginc configs/dvgo/tnt.gin --scene_name playground --ginb run.run_train=False --ginb run.run_eval=False --ginb run.run_render=True`
The error is as below:

> compute_bbox_by_cam_frustrm: xyz_min [-1.2015233 -1.2791067 -1.1872349]
compute_bbox_by_cam_frustrm: xyz_max [1.1897845 1.1122011 1.204073 ]
Traceback (most recent call last):
  File "/home/evsjtu2/yetianxiang/NeRF-Factory/run.py", line 231, in <module>
    run(
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/evsjtu2/yetianxiang/NeRF-Factory/run.py", line 191, in run
    trainer.predict(model, data_module, ckpt_path=ckpt_path)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 874, in predict
    return call._call_and_handle_interrupt(
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 921, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1037, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1286, in _call_setup_hook
    self._call_lightning_module_hook("setup", stage=fn)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/evsjtu2/yetianxiang/NeRF-Factory/src/model/dvgo/model.py", line 399, in setup
    self.render_kwargs = self.get_render_kwargs()
  File "/home/evsjtu2/yetianxiang/NeRF-Factory/src/model/dvgo/model.py", line 816, in get_render_kwargs
    "stepsize": self._stepsize,
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LitDVGO' object has no attribute '_stepsize'
  In call to configurable 'run' (<function run at 0x7fdde3e2aa60>)
compute_bbox_by_cam_frustrm: xyz_min [-1.2015233 -1.2791067 -1.1872349]
compute_bbox_by_cam_frustrm: xyz_max [1.1897845 1.1122011 1.204073 ]
/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py:438: UserWarning: Error handling mechanism for deadlock detection is uninitialized. Skipping check.
  rank_zero_warn("Error handling mechanism for deadlock detection is uninitialized. Skipping check.")
Traceback (most recent call last):
  File "run.py", line 231, in <module>
    run(
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "run.py", line 191, in run
    trainer.predict(model, data_module, ckpt_path=ckpt_path)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 874, in predict
    return call._call_and_handle_interrupt(
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 921, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1037, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1286, in _call_setup_hook
    self._call_lightning_module_hook("setup", stage=fn)
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/evsjtu2/yetianxiang/NeRF-Factory/src/model/dvgo/model.py", line 399, in setup
    self.render_kwargs = self.get_render_kwargs()
  File "/home/evsjtu2/yetianxiang/NeRF-Factory/src/model/dvgo/model.py", line 816, in get_render_kwargs
    "stepsize": self._stepsize,
  File "/home/evsjtu2/miniconda3/envs/nerf_factory/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LitDVGO' object has no attribute '_stepsize'
  In call to configurable 'run' (<function run at 0x7ff3b72a6940>)

Here is my environment setting:

_libgcc_mutex             0.1                        main    anaconda
_openmp_mutex             5.1                       1_gnu    anaconda
aiohttp                   3.8.3                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py38h0a891b7_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.14.6           py38ha65f79e_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
configargparse            1.5.3                    pypi_0    pypi
contourpy                 1.0.6                    pypi_0    pypi
cryptography              37.0.2           py38h2b5fc30_0    conda-forge
cudatoolkit               11.3.1              h9edb442_10    conda-forge
cycler                    0.11.0                   pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2022.11.0                pypi_0    pypi
functorch                 0.1.1                    pypi_0    pypi
gdown                     4.6.0                    pypi_0    pypi
gin-config                0.5.0                    pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.29                   pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
gym                       0.26.2                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
idna                      3.4                pyhd8ed1ab_0    conda-forge
imageio                   2.23.0                   pypi_0    pypi
imageio-ffmpeg            0.4.7                    pypi_0    pypi
importlib-metadata        5.2.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561
jpeg                      9e                   h166bdaf_1    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 11.2.0               h1234567_1    anaconda
libgomp                   11.2.0               h1234567_1    anaconda
libiconv                  1.17                 h166bdaf_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              11.2.0               h1234567_1    anaconda
libtiff                   4.2.0                hf544144_3    conda-forge
libuv                     1.43.0               h7f98852_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
lightning-utilities       0.4.2                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib                3.6.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0            py38h95df7f1_0    conda-forge
mkl_fft                   1.3.1            py38h8666266_1    conda-forge
mkl_random                1.2.2            py38h1abd341_0    conda-forge
multidict                 6.0.3                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3    anaconda
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.8.8                    pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
numpy                     1.23.4           py38h14f4228_0
numpy-base                1.23.4           py38h31eccc5_0
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.6.0.66                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1q               h7f8727e_0    anaconda
packaging                 22.0                     pypi_0    pypi
pandas                    1.5.2                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       22.1.2           py38h06a4308_0    anaconda
piqa                      1.2.2                    pypi_0    pypi
promise                   2.3                      pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.13               h12debd9_0    anaconda
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-lightning         1.8.5.post0              pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.7                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h7f8727e_1    anaconda
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
seaborn                   0.12.1                   pypi_0    pypi
sentry-sdk                1.12.1                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                61.2.0           py38h06a4308_0    anaconda
shortuuid                 1.0.11                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.39.2               h5082296_0    anaconda
tifffile                  2022.10.10               pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    anaconda
torch-efficient-distloss  0.1.3                    pypi_0    pypi
torch-scatter             2.1.0                    pypi_0    pypi
torchaudio                0.11.0               py38_cu113    pytorch
torchmetrics              0.11.0                   pypi_0    pypi
torchvision               0.12.0               py38_cu113    pytorch
tqdm                      4.64.1                   pypi_0    pypi
typing_extensions         4.4.0              pyha770c72_0    conda-forge
urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
wandb                     0.13.7                   pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    anaconda
xz                        5.2.5                h7f8727e_1    anaconda
yarl                      1.8.2                    pypi_0    pypi
zipp                      3.11.0                   pypi_0    pypi
zlib                      1.2.12               h7f8727e_2    anaconda
zstd                      1.5.0                ha95c52a_0    conda-forge

Could you please give me some hints why the errors appear, thanks so much for your help in advance.

**Comment by andrearama** [comment] 2022-12-27 10:46
I do also get this error when using mipnerf360 on multiple gpus, while on one GPUs it seems fine.

It might be also good to check out this (closed) issue https://github.com/kakaobrain/NeRF-Factory/issues/13

**Comment by jeongyw12382** [comment] 2023-01-27 05:22
@andrearama Thanks for mentioning the previous issue.
This is a duplicate of #13. 
According to the issue #13, NaN also appears on the original implementation.
As we are a re-implementation of the original MipNeRF360, we could not handle the numerical stability issue. 
Adjusting hyperparameters might handle this issue.

**Closed as completed by jeongyw12382** 2023-01-27 05:22 UTC
